<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cz.muni.fi.components_generator</groupId>
    <artifactId>components_generator</artifactId>
    <version>1.0.0</version>

    <organization>
        <name>Masaryk University</name>
        <url>https://www.muni.cz/</url>
    </organization>
    <inceptionYear>2025</inceptionYear>
    <developers>
        <developer>
            <id>492791</id>
            <name>Daniel Puchala</name>
        </developer>
    </developers>

    <modules>
        <module>cli</module>
        <module>core</module>
    </modules>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <cpm.toolbox.dir>${project.basedir}/resources/CPM-Toolbox</cpm.toolbox.dir>

        <provtoolbox.version>1.0.0</provtoolbox.version>
        <openprovenance.version>2.2.1</openprovenance.version>

        <maven-shade-plugin.version>3.6.2</maven-shade-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-model</artifactId>
                <version>${openprovenance.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-interop</artifactId>
                <version>${openprovenance.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-nf</artifactId>
                <version>${openprovenance.version}</version>
            </dependency>

            <dependency>
                <groupId>cz.muni.fi.cpm</groupId>
                <artifactId>cpm-core</artifactId>
                <version>${provtoolbox.version}</version>
                <scope>system</scope>
                <systemPath>${cpm.toolbox.dir}/cpm-core-${provtoolbox.version}.jar</systemPath>
            </dependency>
            <dependency>
                <groupId>cz.muni.fi.cpm</groupId>
                <artifactId>cpm-template</artifactId>
                <version>${provtoolbox.version}</version>
                <scope>system</scope>
                <systemPath>${cpm.toolbox.dir}/cpm-template-${provtoolbox.version}.jar</systemPath>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${maven-shade-plugin.version}</version>
                    <configuration>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                        <extraJars>
                            <extraJar>${cpm.toolbox.dir}/cpm-core-${provtoolbox.version}.jar</extraJar>
                            <extraJar>${cpm.toolbox.dir}/cpm-template-${provtoolbox.version}.jar</extraJar>
                        </extraJars>
                        <filters>
                            <filter>
                                <artifact>*:*</artifact>
                                <excludes>
                                    <exclude>META-INF/*.SF</exclude>
                                    <exclude>META-INF/*.DSA</exclude>
                                    <exclude>META-INF/*.RSA</exclude>
                                </excludes>
                            </filter>
                        </filters>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
